In [1]:
import numpy as np

# Vector Multiplication

In [10]:
u = np.random.randint(1,5,4)
v = np.random.randint(2,7,4)

In [13]:
u

array([2, 2, 4, 1])

In [16]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result = result + u[i] *v[i]
    print(result)

In [17]:
u * v

array([ 8, 12, 24,  4])

In [18]:
vector_vector_multiplication(u,v)

48.0


In [19]:
u.dot(v)

48

# Matrix-Vector Multiplication

In [58]:
u = np.random.randint(1,10, 12).reshape((3,4))
u.shape

(3, 4)

In [49]:
v = np.random.randint(2,6,4).reshape(4,1)
v

array([[4],
       [2],
       [3],
       [4]])

In [61]:
def m_v_multiplication(u,v):
    assert u.shape[1] == v.shape[0]
    n = u.shape[0]
    result = np.zeros(n)
    
    for i in range(n):
        result[i] = vector_vector_multiplication(u[i],v)
    print(result)

In [62]:
m_v_multiplication(u,v)

[50.]
[61.]
[75.]
[nan nan nan]


In [57]:
u.dot(v)

array([[48],
       [46],
       [54]])

# Matrix-Matrix Multiplication

In [63]:
def matrix_matrix_multiplication(u,v):
    assert u.shape[1] == v.shape[0]
    
    num_rows= u.shape[0]
    num_cols = v.shape[1]
    result = np.zeros((num_rows * num_cols))
    
    for i in range(num_cols):
        vi = v[:,i]
        uvi = m_v_multiplication(u,vi)
        result[]